# Generated by Django 5.1.2 on 2026-04-16 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True, verbose_name='Agent ID')),
                ('port', models.IntegerField(default=8888, verbose_name='监听端口')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('error', '异常'), ('unknown', '未知')], default='stopped', max_length=20, verbose_name='状态')),
                ('auto_start', models.BooleanField(default=False, verbose_name='开机自启')),
                ('last_start_time', models.DateTimeField(blank=True, null=True, verbose_name='最后启动时间')),
                ('last_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='最后停止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本地 Agent',
                'verbose_name_plural': 'Agent 管理',
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='网卡名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17, verbose_name='MAC地址')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='速率(Mbps)')),
                ('is_management', models.BooleanField(default=False, verbose_name='是否管理网卡')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网卡',
                'verbose_name_plural': '网卡管理',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('type', models.CharField(choices=[('security_device', '安全设备'), ('ic_firewall', '工控防火墙'), ('ic_audit', '工控审计'), ('ids', 'IDS'), ('other', '其他')], default='ic_firewall', max_length=30, verbose_name='设备类型')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='管理端口')),
                ('user', models.CharField(default='admin', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试设备',
                'verbose_name_plural': '测试设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packets_sent', models.BigIntegerField(default=0, verbose_name='已发送报文数')),
                ('packets_received', models.BigIntegerField(default=0, verbose_name='已接收报文数')),
                ('scan_count', models.IntegerField(default=0, verbose_name='扫描次数')),
                ('replay_count', models.IntegerField(default=0, verbose_name='回放次数')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.localagent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent 统计',
                'verbose_name_plural': 'Agent 统计',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='localagent',
            name='interface',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.networkinterface', verbose_name='绑定网卡'),
        ),
    ]
