# Generated by Django 5.1.2 on 2026-04-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='is_up',
            field=models.BooleanField(default=False, verbose_name='是否启动'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='status',
            field=models.CharField(default='DOWN', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
    ]
