# Generated by Django 5.1.2 on 2026-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_networkinterface_is_up_networkinterface_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=100, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP端口')),
                ('sender_email', models.CharField(max_length=100, verbose_name='发件人邮箱')),
                ('sender_password', models.CharField(max_length=200, verbose_name='发件人密码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用SSL')),
                ('recipients', models.TextField(help_text='多个邮箱用换行分隔', verbose_name='收件人邮箱')),
                ('check_interval', models.IntegerField(default=300, verbose_name='监测频率（秒）')),
                ('cpu_threshold', models.IntegerField(default=80, verbose_name='CPU告警阈值（%）')),
                ('memory_threshold', models.IntegerField(default=80, verbose_name='内存告警阈值（%）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警配置',
                'verbose_name_plural': '告警配置',
            },
        ),
        migrations.AddField(
            model_name='testdevice',
            name='backend_password',
            field=models.CharField(blank=True, default='', help_text='后台root密码，留空则使用设备类型默认密码', max_length=200, verbose_name='后台密码'),
        ),
        migrations.AddField(
            model_name='testdevice',
            name='is_long_running',
            field=models.BooleanField(default=False, help_text='长跑环境默认启动监测', verbose_name='长跑环境'),
        ),
        migrations.AlterField(
            model_name='testdevice',
            name='password',
            field=models.CharField(blank=True, default='', help_text='SSH登录密码', max_length=200, verbose_name='SSH密码'),
        ),
        migrations.CreateModel(
            name='DeviceAlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('alert_type', models.CharField(choices=[('cpu', 'CPU告警'), ('memory', '内存告警'), ('coredump', 'Coredump告警')], max_length=20, verbose_name='告警类型')),
                ('alert_value', models.FloatField(help_text='CPU/内存使用率或coredump文件数量', verbose_name='告警值')),
                ('has_alert', models.BooleanField(default=True, verbose_name='是否告警')),
                ('is_ignored', models.BooleanField(default=False, verbose_name='是否已忽略')),
                ('ignore_until', models.DateTimeField(blank=True, help_text='忽略后一周内不再提醒', null=True, verbose_name='忽略截止时间')),
                ('alert_time', models.DateTimeField(auto_now_add=True, verbose_name='告警时间')),
                ('last_email_time', models.DateTimeField(blank=True, null=True, verbose_name='最后发送邮件时间')),
                ('email_sent', models.BooleanField(default=False, verbose_name='已发送邮件')),
            ],
            options={
                'verbose_name': '设备告警状态',
                'verbose_name_plural': '设备告警状态',
                'ordering': ['-alert_time'],
                'indexes': [models.Index(fields=['device_id', 'alert_type'], name='main_device_device__c0286f_idx'), models.Index(fields=['has_alert', 'is_ignored'], name='main_device_has_ale_745cc6_idx')],
            },
        ),
    ]
