# Generated by Django 5.1.2 on 2026-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alertconfig_testdevice_backend_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMonitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_ip', models.GenericIPAddressField(verbose_name='设备IP')),
                ('cpu_usage', models.FloatField(default=0, verbose_name='CPU使用率(%)')),
                ('cpu_name', models.CharField(default='ARM/x86 Processor', max_length=100, verbose_name='CPU型号')),
                ('memory_usage', models.FloatField(default=0, verbose_name='内存使用率(%)')),
                ('memory_used', models.IntegerField(default=0, verbose_name='已用内存(MB)')),
                ('memory_total', models.IntegerField(default=0, verbose_name='总内存(MB)')),
                ('disk_usage', models.FloatField(default=0, verbose_name='磁盘使用率(%)')),
                ('disk_used', models.FloatField(default=0, verbose_name='已用磁盘(GB)')),
                ('disk_total', models.FloatField(default=0, verbose_name='总磁盘(GB)')),
                ('rx_rate', models.IntegerField(default=0, verbose_name='接收速率(B/s)')),
                ('tx_rate', models.IntegerField(default=0, verbose_name='发送速率(B/s)')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误信息')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备监控数据',
                'verbose_name_plural': '设备监控数据',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['device_id'], name='main_device_device__c97d64_idx')],
            },
        ),
    ]
