# Generated by Django 5.1.2 on 2026-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_device_monitor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdevice',
            name='cpu_cores',
            field=models.IntegerField(default=0, help_text='通过 lscpu 获取 CPU(s)', verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='testdevice',
            name='cpu_model',
            field=models.CharField(blank=True, default='', help_text='通过 lscpu 获取 Model name', max_length=200, verbose_name='CPU型号'),
        ),
        migrations.AddField(
            model_name='testdevice',
            name='hardware_model',
            field=models.CharField(blank=True, default='', help_text='通过 show hwtype 获取', max_length=200, verbose_name='硬件型号'),
        ),
    ]
