# Generated by Django 5.1.2 on 2026-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_device_hardware_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='namespace',
            field=models.CharField(blank=True, help_text='网卡所在的namespace，如 ns-eth1。为空表示在主namespace', max_length=50, null=True, verbose_name='Namespace名称'),
        ),
        migrations.CreateModel(
            name='AgentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='用户输入的标识，如 user1、张三', max_length=100, verbose_name='用户标识符')),
                ('client_ip', models.GenericIPAddressField(help_text='访问前端的 IP 地址，用于追踪', verbose_name='客户端 IP')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='租用时间')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='用户最后一次访问 Agent 相关功能的时间', null=True, verbose_name='最后活跃时间')),
                ('expire_at', models.DateTimeField(blank=True, help_text='仅用于显示，实际过期基于 last_activity_at', null=True, verbose_name='过期时间')),
                ('status', models.CharField(choices=[('active', '活跃'), ('expired', '已过期'), ('released', '已释放')], default='active', max_length=20, verbose_name='状态')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('agents', models.ManyToManyField(help_text='被租用的 Agent 组', to='main.localagent', verbose_name='租用的 Agent')),
            ],
            options={
                'verbose_name': 'Agent 租用',
                'verbose_name_plural': 'Agent 租用管理',
                'ordering': ['-locked_at'],
            },
        ),
    ]
