# Generated by Django 5.1.2 on 2026-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_device_hardware_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='namespace',
            field=models.CharField(blank=True, help_text='网卡所在的namespace，如 ns-eth1。为空表示在主namespace', max_length=50, null=True, verbose_name='Namespace名称'),
        ),
    ]