# Generated by Django 5.1.2 on 2026-05-28 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_add_namespace_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='用户输入的标识，如 user1、张三', max_length=100, verbose_name='用户标识符')),
                ('client_ip', models.GenericIPAddressField(help_text='访问前端的 IP 地址，用于追踪', verbose_name='客户端 IP')),
                ('locked_at', models.DateTimeField(auto_now_add=True, verbose_name='租用时间')),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='用户最后一次访问 Agent 相关功能的时间', null=True, verbose_name='最后活跃时间')),
                ('expire_at', models.DateTimeField(blank=True, help_text='仅用于显示，实际过期基于 last_activity_at', null=True, verbose_name='过期时间')),
                ('status', models.CharField(choices=[('active', '活跃'), ('expired', '已过期'), ('released', '已释放')], default='active', max_length=20, verbose_name='状态')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='释放时间')),
                ('agents', models.ManyToManyField(help_text='被租用的 Agent 组', to='main.localagent', verbose_name='租用的 Agent')),
            ],
            options={
                'verbose_name': 'Agent 租用',
                'verbose_name_plural': 'Agent 租用管理',
                'ordering': ['-locked_at'],
            },
        ),
        migrations.CreateModel(
            name='PortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, verbose_name='Agent ID')),
                ('agent_interface', models.CharField(max_length=50, verbose_name='Agent网口名')),
                ('firewall_interface', models.CharField(max_length=50, verbose_name='防火墙网口名')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testdevice', verbose_name='防火墙设备')),
            ],
            options={
                'verbose_name': '网口映射',
                'verbose_name_plural': '网口映射',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='PortTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_session_id', models.CharField(max_length=50, verbose_name='测试会话ID')),
                ('scenario_id', models.IntegerField(verbose_name='场景编号')),
                ('autoneg_config', models.CharField(help_text='on/off', max_length=10, verbose_name='配置-自协商')),
                ('speed_config', models.CharField(max_length=20, verbose_name='配置-速率')),
                ('duplex_config', models.CharField(max_length=20, verbose_name='配置-双工')),
                ('firewall_speed', models.CharField(max_length=20, verbose_name='防火墙-速率')),
                ('firewall_duplex', models.CharField(max_length=20, verbose_name='防火墙-双工')),
                ('firewall_link', models.CharField(max_length=10, verbose_name='防火墙-LINK状态')),
                ('result', models.CharField(help_text='PASS/FAIL/ERROR', max_length=10, verbose_name='测试结果')),
                ('ethtool_output', models.TextField(blank=True, verbose_name='ethtool完整输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='测试时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.testdevice', verbose_name='防火墙设备')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.portmapping', verbose_name='网口映射')),
            ],
            options={
                'verbose_name': '网口测试结果',
                'verbose_name_plural': '网口测试结果',
                'ordering': ['test_session_id', 'scenario_id'],
            },
        ),
    ]
