# Generated by Django 5.1.2 on 2026-05-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20260528_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porttestresult',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portmapping', verbose_name='网口映射'),
        ),
    ]
