# Generated by Django 4.2.30 on 2026-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_linkaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('source_ip', models.GenericIPAddressField(verbose_name='操作IP')),
                ('action', models.CharField(help_text='如：新增设备、删除Agent、启动测试', max_length=100, verbose_name='操作名称')),
                ('resource_type', models.CharField(help_text='如：设备、Agent、系统配置', max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=50, verbose_name='资源ID')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('result', models.CharField(choices=[('success', '成功'), ('failure', '失败'), ('error', '错误')], default='success', max_length=20, verbose_name='执行结果')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='main_operat_timesta_d841cd_idx'), models.Index(fields=['resource_type'], name='main_operat_resourc_0f4400_idx'), models.Index(fields=['action'], name='main_operat_action_8dd320_idx')],
            },
        ),
    ]
